import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Card, Button } from "react-bootstrap";
import Form from "react-bootstrap/Form";
import InputGroup from "react-bootstrap/InputGroup";
import { useRouter } from "next/router";
import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar";
import Dropdown from 'react-bootstrap/Dropdown';
import DropdownButton from 'react-bootstrap/DropdownButton';


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  return (
    <main >
      <Head>
        <title>Web Banking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className={styles.menu} style={{marginBottom: "50px"}}>
          <div className={styles.top} style={{ fontSize: "30px" }}>
            <div>Webbank</div>
          </div>
          <div style={{justifyItem:"right"}}>
          <DropdownButton
      align="end"
      title="Username"
      id="dropdown-menu-align-end"
      variant="success"
    >
      <Dropdown.Item eventKey="1"
      style={{
        cursor: "pointer"
      }}
      onClick={() => {
        router.push("/menu");
      }} >Menu</Dropdown.Item>
      
      <Dropdown.Divider />
      <Dropdown.Item eventKey="4"
      style={{
        cursor: "pointer"
      }}
      onClick={() => {
        router.push("/");
      }} 
      >Sign Out</Dropdown.Item>
      </DropdownButton>
            </div>
        </div>
    
        <div className={styles.card}>
          <Card style={{ width: "30rem" }}>
            <Card.Body>
              <Card.Title style={{ textAlign: "center" }}>ยอดเงินในบัญชี</Card.Title>
              <div>
               
                <Card>
                    <Card.Body style={{ textAlign: "center" }}>100,000 THB</Card.Body>
                    </Card>
              </div>
              
              
            </Card.Body>
          </Card>
        </div>
        <div className={styles.card} style={{ marginTop: "50px"}}>
        <Card style={{ width: "50rem" }}>
            <Card.Body style={{padding: "20px 50px"}}>
              <Card.Title style={{ textAlign: "center" }}>ประวัติการใช้งาน</Card.Title>
              <div>
                <Card style={{marginBottom: "20px"}}> 
                    <Card.Header className={styles.cardhistory}>2023-03-16T15:00:00Z</Card.Header>
                    <Card.Body>โอนเงิน : 500,000 THB</Card.Body>          
                </Card>
                <Card style={{marginBottom: "20px"}}> 
                    <Card.Header className={styles.cardhistory}>2023-03-16T12:00:00Z</Card.Header>
                    <Card.Body>รายการเงินเข้า : 1,000,000 THB</Card.Body>          
                </Card>
                <Card style={{marginBottom: "20px"}}> 
                    <Card.Header className={styles.cardhistory}>2023-03-15T13:00:00Z</Card.Header>
                    <Card.Body>รายการเงินออก : 20,000 THB</Card.Body>          
                </Card>
                {new Array(10).fill('').map((v,k) => {
                    return <div key={k}><Card style={{marginBottom: "20px"}}> 
                    <Card.Header className={styles.cardhistory}>2023-03-15T13:00:00Z</Card.Header>
                    <Card.Body>รายการเงินออก : 20,000 THB</Card.Body>          
                    </Card>
                    </div>
                    })}
                
              </div>
              
              
            </Card.Body>
          </Card>
        </div>
      </div>
    </main>
  );
}